name: Ubuntu 22.04
on:
  push:
    branches:
      - main
      - "*-next"
  pull_request:
    branches:
      - main
      - "*-next"

jobs:
  setup-test:
    name: setup test

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run setup test
      run: ./tests/script/setup_test.sh
